### ISSUE TITLE
docs search is broken on canonical.com/data/docs

### ISSUE THREAD

**Issue by grobbie** [canonical/canonical.com#1071]
## Summary

When using the search box of any docs page within canonical.com, no results are returned for any query. For example searching for "spark" in the charmed spark documentation set results in no results https://canonical.com/data/docs/spark/k8s/search?q=spark&siteSearch=%2Fdata%2Fdocs%2Fspark-k8s

## Process

Go to https://canonical.com/data/docs and pick any product. Type the product name into the search box at the top of the page. See no results

## Current and expected result

Current result - no results from any search whatever criteria

Expected result - sensibly indexed results are returned ranked by relevance

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/3254480/f818a5f9-856b-4b4f-b0bd-31875495b40d)

## Browser details

N/A server side issue happens on any browser

**Comment by akbarkz** [comment]
This is happening because we use Google custom search API and currently Google is still not indexing due to the work we are doing [on navigation](https://github.com/canonical/canonical.com/pull/1056)

Even if we start indexing, it may take days for Google to actually index these pages for them to be searchable.

If you really need to use search you can still use https://ubuntu.com/data/docs

**Comment by akbarkz** [comment]
This is happening because we use Google custom search API and currently Google is still not indexing due to the work we are doing [on navigation](https://github.com/canonical/canonical.com/pull/1056)

Even if we start indexing, it may take days for Google to actually index these pages for them to be searchable.

If you really need to use search you can still use https://ubuntu.com/data/docs
