### ISSUE TITLE
Incorrect numbers in the list of stages on the candidate page

### ISSUE THREAD

**Issue by sukhodiy** [canonical/canonical.com#1219]
## Summary

On the candidate page, instead of the stage number, zeros are now displayed (see screenshot below). As far as I remember, this broke quite recently, so apparently the reason was one of the latest site updates.

## Steps to reproduce the behavior

1. Go to https://canonical.com/careers/application/[id]
2. Scroll down to 'Your application process'.

## Expected behavior

Sequence numbers (or perhaps some other numbers) for each stage.

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/59742717/66985ad7-6dc8-4601-ae4e-acb9cb28b042)

## Browser/device details

- Device: DELL laptop
- OS: Ubuntu 22.04.4 LTS (64-bit)
- Browsers:
  - Firefox 123.0.1 (64-bit)
  - Google Chrome 122.0.6261.128 (Official Build) (64-bit)

**Comment by johnwangwyx** [comment]
I am having the same issue on my application page. I tried to inspect the element and I can see the values are updated by the line `content: counter(li)` in `static/sass/_pattern_application.scss`

https://github.com/canonical/canonical.com/blob/655b9c9164f26bac9b74fef3dc84a894a2d396f2/static/sass/_pattern_application.scss#L70

I also see that this repo recently bumped the vanilla-framework to 4.9.0 (#1210) 4 days ago and one of the changes for 4.9.0 is to rename `li` to `list-item` and so as the `counter-increment: list-item`

https://github.com/canonical/vanilla-framework/pull/5011/files#diff-3a3fa7278b1cf97af2a55b563c936d896aedf1733d22b950a13363e19f7afed0R8-R20

I am wondering if this is the root cause for this issue? (i.e the `counter-increment` only increment the element `list-item` in the new version rather than `li`)
