### ISSUE TITLE
Interview Status

### ISSUE THREAD

**Issue by dhavallunawat01** [canonical/canonical.com#1277]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

I am interviewing. Why can't I access the page?

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/173500440/6505767c-927d-4dac-b920-945c59cc1f47)

## Browser/device details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by lizzochek** [comment]
Hello @dhavallunawat01. Thank you for filing as issue. This happens when the candidate is either rejected or applied to a different position. If you were rejected, you should have received an email. If you believe there has been a mistake and you were not rejected, please open a new issue specifying that and we will look into it
