### ISSUE TITLE
[c.c application page] Ensure demos can send rejection emails

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#627]
It is also central to the whole of the withdrawal flow, is used in the request_withdrawal view. And, when we built that flow in #593, we clearly didn't test the actual sending of the email, instead skipping that step in development mode and simply echoing the contents of the email that would have been sent back out onto the page.

So I think it's prudent to check that the email flow works here. As well as this, it is important that we treat the demos as a real environment that should work exactly as production does. Now that we've discovered a place where it doesn't (the email sending hangs) it's definitely good practice to make sure we resolve that issue before simply moving on.

**Comment by nottrobin** [comment]
Thanks for filing this Ant. An update: [The RT to open up the firewall so that the demo service can reach the SMTP server](https://portal.admin.canonical.com/C153188/) has been completed.

However, we now get [an authentication error](https://pastebin.canonical.com/p/vKxP64hZnM/). I've checked and I'm 99% sure the credentials are identical between demos and production, so I *suspect* that this authentication errors also exists on production.

Let's check and fix it.
