### ISSUE TITLE
Canonical & Ubuntu lack "Impressum"

### ISSUE THREAD

**Issue by Lin-Admin** [canonical/canonical.com#678]
## Summary

Companies who address  products or services towards the European Union are obliged to present a page called "Impressum" showing some precisely defined company information.

Although Great Britain has left the EU, this obligation is still valid.

## Current and expected result

Add this page with a Link on each displayed page.

**Comment by petesfrench** [comment]
@anthonydillon do you know if this is something we need to do?

**Comment by petesfrench** [comment]
I spoke with our legal department and they informed me that we have no legal obligation to provide an Impressum. Please see our privacy policy for more details: https://ubuntu.com/legal/data-privacy

**Comment by sowasred2012** [comment]
@petesfrench who did you speak to in Legal? There's an open request regarding this in Salesforce: https://canonical.lightning.force.com/lightning/r/Legal__c/a0q4K000003B5a0QAC/view

**Comment by petesfrench** [comment]
@sowasred2012 I asked in the 'legal team' mattermost channel and Lydia Pagoni responded

**Comment by Lin-Admin** [comment]
I am just amused to see Canonical spinning...
The legal situation is clear and simple:
a) With the UK being no longer a member of the EU, the laws of EU are no longer directly applicable.
b) However, the EU stipulates that any company of the world offering materials or services to members of the EU has to fulfill EU consumer laws. 
c) Since Canonical offers it's services also to EU, it has to follow paragraph b) which requires an Impressum on websites.

And beside legal aspects: 
Why does Canonical try to refuse such a simple request? What shall be hidden??

**Comment by fitojb** [comment]
@Lin-Admin Please refrain from making speculation and attacking people. Also, this is not “EU law” as you say — the requirement is in art. 5 of the Telemediengesetz, and it’s not required for the purpose of providing services to people in the EU: all it does is stating the ownership or authorship of your website’s contents, and that’s why German bloggers have one, not because they “offer services” to anybody. At TDF we have an Impressum because we’re incorporated in Germany, but that’s it.

**Comment by lizzochek** [comment]
It was confirmed with the legal team that we are not required to have an Impressum
