### ISSUE TITLE
Re-enable application withdrawal when it has been fixed

### ISSUE THREAD

**Issue by petesfrench** [canonical/canonical.com#742]
## Summary

- Application withdrawal was temporarly disbaled in [this pr](https://github.com/canonical/canonical.com/pull/741), we need to re-enable it once a fix has been found

**Comment by jkfran** [comment]
The issue is happening when the app tries to send an email. I look into it, and it seems to be an authentication issue. I [reported this issue to IS](https://portal.admin.canonical.com/C155503/).

If it was the credentials, IS would give us new ones and we just need to update the secrets on production with no changes in the codebase.

**Comment by anthonydillon** [comment]
This is working again now
