### ISSUE TITLE
Candidate Page ( careers/application) throws error 500

### ISSUE THREAD

**Issue by teocez** [canonical/canonical.com#755]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary

I cannot track my application due to error 500.

## Process

Accessed link  _https://canonical.com/careers/application._

## Current and expected result

Access my candidate page and see my current applications to open roles

## Screenshot

![image](https://user-images.githubusercontent.com/122680504/212474725-5d04a237-c3a9-438b-b701-9675441b0d16.png)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by nottrobin** [comment]
Hi @teocez, thanks for reporting this. I'd like to fix this as a priority. Could you tell me - how did you get to this page?

**Comment by teocez** [comment]
Hi @nottrobin. The link was shared to me to track my application to an open position.

**Comment by nottrobin** [comment]
In an email? I think normally these links should be of the form `https://canonical.com/careers/application/{someverylongtoken}`.

Without the token, or with a long token, it shows a 500. Which isn't a great experience, and I can fix that up, but fundamentally you won't be able to access the page without the correct token.

Do you have a link with a token? Or was the token missing in the communication you received? Because if you weren't sent a link with a token then that's an error and we should chase up how that link got to you.

**Comment by nottrobin** [comment]
https://github.com/canonical/canonical.com/pull/756 is the best I can do for now, without more information.

I'll let that PR close this issue when it's merged, but feel free to reply with more information and we can look into it further.

**Comment by teocez** [comment]
Sorry for the delay in my reply. I received the link without the token so it makes sense I get the 500 error. I will go back to the sender and check for another link.
Thank you @nottrobin !
